output: docs/
clean: true
exclude: Tests/
swift_version: 3.0.2
author: Timofey Solomko
module: SWCompression
module_version: 2.0.0
copyright: '© 2016 Timofey Solomko'
readme: README.md
github_url: https://github.com/tsolomko/SWCompression
github_file_prefix: https://github.com/tsolomko/SWCompression/tree/v2.0.0
skip_undocumented: true
theme: fullwidth
