output: docs/
clean: true
exclude: Tests/
author: Timofey Solomko
module: SWCompression
module_version: 3.3.0-test.2
copyright: '© 2017 Timofey Solomko'
readme: README.md
github_url: https://github.com/tsolomko/SWCompression
github_file_prefix: https://github.com/tsolomko/SWCompression/tree/v3.3.0-test.2
theme: fullwidth

custom_categories:
    - name: Compression
      children:
      - BZip2
      - Deflate
      - LZMA
      - LZMA2
    - name: Archives
      children:
      - GzipArchive
      - GzipHeader
      - ZlibArchive
      - ZlibHeader
      - XZArchive
    - name: Containers
      children:
      - ZipContainer
      - ZipEntry
      - TarContainer
      - TarEntry
    - name: Errors
      children:
      - BZip2Error
      - DeflateError
      - GzipError
      - LZMA2Error
      - LZMAError
      - TarError
      - XZError
      - ZipError
      - ZlibError
    - name: Protocols
      children:
      - Archive
      - Container
      - ContainerEntry
      - DecompressionAlgorithm
