excluded:
  - .build/
disabled_rules:
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - type_body_length
opt_in_rules:
  - array_init
  - block_based_kvo
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - discouraged_direct_init
  - discouraged_object_literal
  - explicit_init
  - fatal_error_message
  - first_where
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - literal_expression_end_indentation
  - no_grouping_extension
  - operator_usage_whitespace
  - pattern_matching_keywords
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - yoda_condition
